### ISSUE TITLE
Challenge is zero

### ISSUE THREAD

**Issue by jimouris** [DaylightingSociety/Paillier#8]
In ZKP, the challenge_string is 0.

https://github.com/DaylightingSociety/Paillier/blob/master/lib/paillier/zkp.rb#L118

Printing the challenge string in both lines [109](https://github.com/DaylightingSociety/Paillier/blob/master/lib/paillier/zkp.rb#L109) and [178](https://github.com/DaylightingSociety/Paillier/blob/master/lib/paillier/zkp.rb#L178) like `puts("challenge_string", OpenSSL::BN.new(challenge_string.to_i))` returns a 0. If it is another value, I don't see how the test in line [186](https://github.com/DaylightingSociety/Paillier/blob/master/lib/paillier/zkp.rb#L186) can be successful.

**Comment by tfdahlin** [comment]
I'll look into this when I have a little bit of spare time!

**Comment by jimouris** [comment]
Thank you!

**Comment by tfdahlin** [comment]
hi @jimouris sorry for the delay, but I believe I've fixed this issue in the latest push to the repository. It turns out the issue was from the call to `to_i`. I thought I had tested the code more thoroughly back when I wrote the zkp portion of this library, but I must have missed that silent failure somehow. This should now convert the sha256 digest into an actual bignum, instead of failing on the first byte and making the challenge_string set to 0.

@milo-trujillo can you update the ruby gem when you get the chance? I've updated the version number in the gemspec file as well as the changelog.

**Comment by tfdahlin** [comment]
@jimouris the new code should be available through rubygems now

**Comment by jimouris** [comment]
Thank you!
